/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guis.panels;

/**
 *
 * @author Nicolas Matute M.Z <manuelnmatute@gmail.com>
 */
public class AssetsPanel extends javax.swing.JPanel {

    /**
     * Creates new form Home
     */
    public AssetsPanel() {
        setSize(640, 570);
        initComponents();
        amount.setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AssetsPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        addButton = new guis.RSButtonMetro();
        jScrollPane3 = new javax.swing.JScrollPane();
        AssetsTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        category = new javax.swing.JComboBox<>();
        amount = new javax.swing.JTextField();
        amount1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setName("Home"); // NOI18N
        setLayout(new java.awt.CardLayout());

        AssetsPanel.setBackground(new java.awt.Color(235, 236, 240));
        AssetsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ACTIVOS");
        AssetsPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 10, 250, 50));

        addButton.setBackground(new java.awt.Color(255, 0, 0));
        addButton.setText("AGREGAR");
        addButton.setColorHover(new java.awt.Color(26, 46, 54));
        addButton.setColorNormal(new java.awt.Color(255, 0, 0));
        addButton.setColorPressed(new java.awt.Color(26, 46, 54));
        addButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        AssetsPanel.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, -1, 50));

        AssetsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Valor", "Cuenta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(AssetsTable);
        if (AssetsTable.getColumnModel().getColumnCount() > 0) {
            AssetsTable.getColumnModel().getColumn(0).setResizable(false);
            AssetsTable.getColumnModel().getColumn(1).setResizable(false);
            AssetsTable.getColumnModel().getColumn(2).setResizable(false);
        }

        AssetsPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 580, 280));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CUENTA");
        AssetsPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, 90, 20));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("VALOR");
        AssetsPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 90, 20));

        category.setBackground(new java.awt.Color(26, 46, 54));
        category.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        category.setForeground(new java.awt.Color(255, 255, 255));
        category.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        category.setOpaque(false);
        category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryActionPerformed(evt);
            }
        });
        AssetsPanel.add(category, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 160, 30));

        amount.setBackground(new java.awt.Color(255, 255, 255));
        amount.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        amount.setForeground(new java.awt.Color(0, 0, 0));
        amount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        amount.setOpaque(false);
        amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountActionPerformed(evt);
            }
        });
        AssetsPanel.add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 170, 30));

        amount1.setBackground(new java.awt.Color(255, 255, 255));
        amount1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        amount1.setForeground(new java.awt.Color(0, 0, 0));
        amount1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        amount1.setOpaque(false);
        amount1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amount1ActionPerformed(evt);
            }
        });
        AssetsPanel.add(amount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 90, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("NOMBRE");
        AssetsPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 90, 20));

        add(AssetsPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_addButtonActionPerformed

    private void categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryActionPerformed

    private void amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountActionPerformed

    private void amount1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amount1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amount1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AssetsPanel;
    private javax.swing.JTable AssetsTable;
    private guis.RSButtonMetro addButton;
    private javax.swing.JTextField amount;
    private javax.swing.JTextField amount1;
    private javax.swing.JComboBox<String> category;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
