/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guis.panels;

/**
 *
 * @author Nicolas Matute M.Z <manuelnmatute@gmail.com>
 */
public class Home extends javax.swing.JPanel {

    /**
     * Creates new form Home
     */
    public Home() {
        setSize(640, 570);
        initComponents();
        amount.setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        category = new javax.swing.JComboBox<>();
        product = new javax.swing.JComboBox<>();
        amount = new javax.swing.JTextField();
        sellButton = new guis.RSButtonMetro();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        addButton = new guis.RSButtonMetro();
        reportButton = new guis.RSButtonMetro();

        setName("Home"); // NOI18N
        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(235, 236, 240));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        category.setBackground(new java.awt.Color(26, 46, 54));
        category.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        category.setForeground(new java.awt.Color(255, 255, 255));
        category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Producto", "Servicio" }));
        category.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        category.setOpaque(false);
        category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryActionPerformed(evt);
            }
        });
        jPanel1.add(category, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 110, 30));

        product.setBackground(new java.awt.Color(26, 46, 54));
        product.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        product.setForeground(new java.awt.Color(255, 255, 255));
        product.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        product.setOpaque(false);
        jPanel1.add(product, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 190, 30));

        amount.setBackground(new java.awt.Color(255, 255, 255));
        amount.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        amount.setForeground(new java.awt.Color(0, 0, 0));
        amount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        amount.setOpaque(false);
        amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountActionPerformed(evt);
            }
        });
        jPanel1.add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 110, 50));

        sellButton.setBackground(new java.awt.Color(255, 0, 0));
        sellButton.setText("VENDER");
        sellButton.setColorHover(new java.awt.Color(26, 46, 54));
        sellButton.setColorNormal(new java.awt.Color(255, 0, 0));
        sellButton.setColorPressed(new java.awt.Color(26, 46, 54));
        sellButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(sellButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, -1, 50));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NOMBRE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 90, 20));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CATEGORIA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 90, 20));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 580, 320));

        addButton.setBackground(new java.awt.Color(255, 0, 0));
        addButton.setText("AGREGAR");
        addButton.setColorHover(new java.awt.Color(26, 46, 54));
        addButton.setColorNormal(new java.awt.Color(255, 0, 0));
        addButton.setColorPressed(new java.awt.Color(26, 46, 54));
        addButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, -1, 50));

        reportButton.setBackground(new java.awt.Color(255, 0, 0));
        reportButton.setText("Generar Informe");
        reportButton.setColorHover(new java.awt.Color(26, 46, 54));
        reportButton.setColorNormal(new java.awt.Color(255, 0, 0));
        reportButton.setColorPressed(new java.awt.Color(26, 46, 54));
        reportButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        reportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportButtonActionPerformed(evt);
            }
        });
        jPanel1.add(reportButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, 180, 50));

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountActionPerformed

    private void categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_addButtonActionPerformed

    private void reportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reportButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private guis.RSButtonMetro addButton;
    private javax.swing.JTextField amount;
    private javax.swing.JComboBox<String> category;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> product;
    private guis.RSButtonMetro reportButton;
    private guis.RSButtonMetro sellButton;
    // End of variables declaration//GEN-END:variables
}
